server:
  port: 9990

#activemq
spring:
  activemq:
    user: admin
    password: admin
    broker-url: tcp://47.101.133.169:61616
  jms:
    pub-sub-domain: true #true->topic

#自定义topic名称
mytopic: boot-activemq-topic